# Generated by Django 6.0.6 on 2026-06-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pending_itinerary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
