# Generated by Django 6.0.6 on 2026-06-27 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingactivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_activities', to='catalog.activity'),
        ),
        migrations.AddField(
            model_name='bookingactivity',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingflight',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingflight',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_flights', to='catalog.flight'),
        ),
        migrations.AddField(
            model_name='bookinghotelstay',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_stays', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookinghotelstay',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_stays', to='catalog.hotel'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingflight',
            unique_together={('booking', 'direction')},
        ),
        migrations.AlterUniqueTogether(
            name='bookinghotelstay',
            unique_together={('booking', 'date')},
        ),
    ]
